export const mockTransactionInfo = {
  traceId: 'ad-ui7-6f5bcfbc9d-5z4zm^1747900102753^57128454',
  spanId: 8304442929524212000,
  agentId: 'ad-ui7-6f5bcfbc9d-5z4zm',
  callStackStart: 1751350019009,
  callStackEnd: 1751350019356,
};

export const mockData = {
  traceEvents: [
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1751350019009000,
      ph: 'X',
      dur: 347000,
      s: 'p',
      name: '[APIGW-DEV-AD1] Vert.x HTTP Server',
      cname: '',
      args: {
        id: '1',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '0',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1751350019009000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'handle(HttpServerRequest request)',
      cname: '',
      args: {
        id: '6',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '1',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '0',
      ts: 1751350019014000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '6',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '1',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '0',
      ts: 1751350019014000,
      ph: 'f',
      dur: 341000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '16', 'API Type': 'TOMCAT', 'Application Name': 'VOD.PLAYAPI3', parentId: '14' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019014000,
      ph: 'X',
      dur: 341000,
      s: 'p',
      name: '[VOD.PLAYAPI3] Servlet Process',
      cname: 'grey',
      args: { id: '16', 'API Type': 'TOMCAT', 'Application Name': 'VOD.PLAYAPI3', parentId: '14' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019014000,
      ph: 'X',
      dur: 341000,
      s: 'p',
      name: 'invoke(Request request, Response response)',
      cname: 'grey',
      args: {
        id: '21',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '16',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019015000,
      ph: 'X',
      dur: 339000,
      s: 'p',
      name: 'doGet(HttpServletRequest request, HttpServletResponse response)',
      cname: 'grey',
      args: { id: '23', 'API Type': 'SPRING', 'Application Name': 'VOD.PLAYAPI3', parentId: '21' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019016000,
      ph: 'X',
      dur: 337000,
      s: 'p',
      name: 'playbackV2(String videoId, PlaybackRequest playbackRequest, HttpServletRequest servletRequest)',
      cname: 'grey',
      args: {
        id: '24',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '23',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019017000,
      ph: 'X',
      dur: 336000,
      s: 'p',
      name: 'playback(PlayContext context)',
      cname: 'grey',
      args: {
        id: '28',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '24',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019017000,
      ph: 'X',
      dur: 317000,
      s: 'p',
      name: 'getVideoV2(String videoId)',
      cname: 'grey',
      args: {
        id: '29',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '28',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019017000,
      ph: 'X',
      dur: 315000,
      s: 'p',
      name: 'getInputStream()',
      cname: 'grey',
      args: {
        id: '30',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '29',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '1',
      ts: 1751350019023000,
      ph: 's',
      dur: 315000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '30',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '29',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '1',
      ts: 1751350019023000,
      ph: 'f',
      dur: 309000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '31',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '30',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019023000,
      ph: 'X',
      dur: 309000,
      s: 'p',
      name: '[VOD.NEXUS] Servlet Process',
      cname: 'grey',
      args: {
        id: '31',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '30',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019023000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'onStateChange(Connection connection, ConnectionObserver$State newState)',
      cname: 'grey',
      args: {
        id: '37',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '31',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '2',
      ts: 1751350019024000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '37',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '31',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '2',
      ts: 1751350019024000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '39', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '37' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019024000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: 'grey',
      args: { id: '39', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '37' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019024000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'onInboundComplete()',
      cname: 'grey',
      args: {
        id: '40',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '39',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '3',
      ts: 1751350019028000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '40',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '39',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '3',
      ts: 1751350019028000,
      ph: 'f',
      dur: 302000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '49', 'API Type': 'TOMCAT', 'Application Name': 'VOD.API', parentId: '48' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019028000,
      ph: 'X',
      dur: 302000,
      s: 'p',
      name: '[VOD.API] Servlet Process',
      cname: 'grey',
      args: { id: '49', 'API Type': 'TOMCAT', 'Application Name': 'VOD.API', parentId: '48' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019028000,
      ph: 'X',
      dur: 302000,
      s: 'p',
      name: 'invoke(Request request, Response response)',
      cname: 'grey',
      args: {
        id: '54',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'VOD.API',
        parentId: '49',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019028000,
      ph: 'X',
      dur: 301000,
      s: 'p',
      name: 'doGet(HttpServletRequest request, HttpServletResponse response)',
      cname: 'grey',
      args: { id: '56', 'API Type': 'SPRING', 'Application Name': 'VOD.API', parentId: '54' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019029000,
      ph: 'X',
      dur: 299000,
      s: 'p',
      name: 'getVideoV2(String version, String videoId, boolean webPath, HttpServletRequest request)',
      cname: 'grey',
      args: { id: '58', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '56' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019029000,
      ph: 'X',
      dur: 2000,
      s: 'p',
      name: 'get(long duration, TimeUnit units)',
      cname: 'grey',
      args: {
        id: '62',
        'API Type': 'ARCUS(3b96cc2d7c7a4638aeb3eb7b1c0ca58e)',
        'Application Name': 'VOD.API',
        parentId: '58',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019031000,
      ph: 'X',
      dur: 288000,
      s: 'p',
      name: 'getVideoFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '66', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '58' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019031000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'getVideoMasterIdFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '70', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019037000,
      ph: 'X',
      dur: 26000,
      s: 'p',
      name: 'getThumbnailsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '75', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019042000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'validateVideoID(String videoId)',
      cname: 'grey',
      args: { id: '80', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '75' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019043000,
      ph: 'X',
      dur: 20000,
      s: 'p',
      name: 'getAnimatedThumbnailFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '83', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '75' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019063000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'validateVideoID(String videoId)',
      cname: 'grey',
      args: { id: '92', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019064000,
      ph: 'X',
      dur: 5000,
      s: 'p',
      name: 'getSeekingThumbnailsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '95', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019069000,
      ph: 'X',
      dur: 21000,
      s: 'p',
      name: 'getManifestsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '100', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019069000,
      ph: 'X',
      dur: 21000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '104',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '100',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019091000,
      ph: 'X',
      dur: 71000,
      s: 'p',
      name: 'getQualitiesFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '123', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019091000,
      ph: 'X',
      dur: 10000,
      s: 'p',
      name: 'getQualityIdsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '124',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '123',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019101000,
      ph: 'X',
      dur: 17000,
      s: 'p',
      name: 'getQualityFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '132',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '123',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019101000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'getQualityHeaderFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '133',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '132',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019107000,
      ph: 'X',
      dur: 11000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '138',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '132',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019118000,
      ph: 'X',
      dur: 18000,
      s: 'p',
      name: 'getQualityFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '146',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '123',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019118000,
      ph: 'X',
      dur: 7000,
      s: 'p',
      name: 'getQualityHeaderFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '147',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '146',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019125000,
      ph: 'X',
      dur: 11000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '152',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '146',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019136000,
      ph: 'X',
      dur: 14000,
      s: 'p',
      name: 'getQualityFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '160',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '123',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019136000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'getQualityHeaderFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '161',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '160',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019142000,
      ph: 'X',
      dur: 8000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '166',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '160',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019150000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'getQualityFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '174',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '123',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019150000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'getQualityHeaderFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '175',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '174',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019153000,
      ph: 'X',
      dur: 9000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId, String qualityId)',
      cname: 'grey',
      args: {
        id: '180',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '174',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019162000,
      ph: 'X',
      dur: 21000,
      s: 'p',
      name: 'getAudioUnitsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '188', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019162000,
      ph: 'X',
      dur: 21000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '192',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '188',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019183000,
      ph: 'X',
      dur: 81000,
      s: 'p',
      name: 'getVideoDataFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '211', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019193000,
      ph: 'X',
      dur: 26000,
      s: 'p',
      name: 'getProtocolsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '221',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '211',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019219000,
      ph: 'X',
      dur: 24000,
      s: 'p',
      name: 'getPlayCount(String videoId)',
      cname: 'grey',
      args: {
        id: '242',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '211',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019219000,
      ph: 'X',
      dur: 24000,
      s: 'p',
      name: 'execute()',
      cname: 'grey',
      args: {
        id: '243',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.API',
        parentId: '242',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019219000,
      ph: 'X',
      dur: 24000,
      s: 'p',
      name: 'intercept(Interceptor$Chain chain)',
      cname: 'grey',
      args: {
        id: '244',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.API',
        parentId: '243',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '4',
      ts: 1751350019226000,
      ph: 's',
      dur: 24000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '244',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.API',
        parentId: '243',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '4',
      ts: 1751350019226000,
      ph: 'f',
      dur: 17000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '246',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '244',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '',
      ts: 1751350019226000,
      ph: 'X',
      dur: 17000,
      s: 'p',
      name: '[APIGW-DEV-AD1] Vert.x HTTP Server',
      cname: '',
      args: {
        id: '246',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '244',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019221000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: '[VOD.API] connect(int connectTimeout, int readTimeout, int writeTimeout, int pingIntervalMillis, boolean connectionRetryEnabled, Call call, EventListener eventListener)',
      cname: 'grey',
      args: {
        id: '267',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.API',
        parentId: '244',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019244000,
      ph: 'X',
      dur: 19000,
      s: 'p',
      name: 'getVideoUnitsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '272',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '211',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019264000,
      ph: 'X',
      dur: 10000,
      s: 'p',
      name: 'getVideoStatusFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '291', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019268000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'getErrorsFromSecondary(String videoId)',
      cname: 'grey',
      args: {
        id: '298',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.API',
        parentId: '291',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019274000,
      ph: 'X',
      dur: 7000,
      s: 'p',
      name: 'getCopyrightFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '305', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019281000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'getContentInfoFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '312', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019287000,
      ph: 'X',
      dur: 5000,
      s: 'p',
      name: 'getCaptionsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '319', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019292000,
      ph: 'X',
      dur: 4000,
      s: 'p',
      name: 'getQualityVideoIdMapsFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '327', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019296000,
      ph: 'X',
      dur: 23000,
      s: 'p',
      name: 'getRecentLoudnessNormalizationFromSecondary(String videoId)',
      cname: 'grey',
      args: { id: '335', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '66' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019319000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: 'set(String key, int exp, Object o)',
      cname: 'grey',
      args: {
        id: '344',
        'API Type': 'ARCUS(3b96cc2d7c7a4638aeb3eb7b1c0ca58e)',
        'Application Name': 'VOD.API',
        parentId: '58',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019325000,
      ph: 'X',
      dur: 2000,
      s: 'p',
      name: 'get(long duration, TimeUnit units)',
      cname: 'grey',
      args: {
        id: '347',
        'API Type': 'ARCUS(3b96cc2d7c7a4638aeb3eb7b1c0ca58e)',
        'Application Name': 'VOD.API',
        parentId: '58',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019327000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'convertVideoToV2(Video video)',
      cname: 'grey',
      args: { id: '349', 'API Type': 'SPRING_BEAN', 'Application Name': 'VOD.API', parentId: '58' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019328000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'writeValue(JsonGenerator g, Object value)',
      cname: 'grey',
      args: { id: '350', 'API Type': 'JACKSON', 'Application Name': 'VOD.API', parentId: '56' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '5',
      ts: 1751350019329000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '40',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '39',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '5',
      ts: 1751350019329000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '354', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '43' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '',
      ts: 1751350019329000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: '[VOD.NEXUS] Asynchronous Invocation',
      cname: 'grey',
      args: { id: '354', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '43' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '',
      ts: 1751350019329000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'onInboundNext(ChannelHandlerContext ctx, Object msg)',
      cname: 'grey',
      args: {
        id: '355',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '354',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '6',
      ts: 1751350019331000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '37',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '31',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '6',
      ts: 1751350019331000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '362', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '37' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '',
      ts: 1751350019331000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: 'grey',
      args: { id: '362', 'API Type': 'ASYNC', 'Application Name': 'VOD.NEXUS', parentId: '37' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '',
      ts: 1751350019331000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'onComplete()',
      cname: 'grey',
      args: {
        id: '363',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '362',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019023000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'subscribe(CoreSubscriber subscriber)',
      cname: 'grey',
      args: { id: '368', 'API Type': 'REACTOR', 'Application Name': 'VOD.NEXUS', parentId: '37' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019017000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: '[VOD.PLAYAPI3] connect()',
      cname: 'grey',
      args: {
        id: '374',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '30',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1751350019332000,
      ph: 'X',
      dur: 2000,
      s: 'p',
      name: 'readValue(InputStream src, JavaType valueType)',
      cname: 'grey',
      args: {
        id: '379',
        'API Type': 'JACKSON',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '29',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '7',
      ts: 1751350019341000,
      ph: 's',
      dur: 336000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '28',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '24',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '7',
      ts: 1751350019341000,
      ph: 'f',
      dur: 12000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '381', 'API Type': 'ASYNC', 'Application Name': 'VOD.PLAYAPI3', parentId: '380' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: 'grey',
      args: { id: '381', 'API Type': 'ASYNC', 'Application Name': 'VOD.PLAYAPI3', parentId: '380' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'call()',
      cname: 'grey',
      args: {
        id: '382',
        'API Type': 'SPRING_ASYNC',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '381',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'resolve(PlayContext context)',
      cname: 'grey',
      args: {
        id: '383',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '382',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019342000,
      ph: 'X',
      dur: 8000,
      s: 'p',
      name: 'bulk(BulkRequest request)',
      cname: 'grey',
      args: {
        id: '384',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '383',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019342000,
      ph: 'X',
      dur: 4000,
      s: 'p',
      name: 'getOutputStream()',
      cname: 'grey',
      args: {
        id: '386',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '384',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '8',
      ts: 1751350019348000,
      ph: 's',
      dur: 4000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '386',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '384',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '8',
      ts: 1751350019348000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '387', 'API Type': 'TOMCAT', 'Application Name': 'VOD.CDN-DOK', parentId: '386' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: '[VOD.CDN-DOK] Servlet Process',
      cname: 'grey',
      args: { id: '387', 'API Type': 'TOMCAT', 'Application Name': 'VOD.CDN-DOK', parentId: '386' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'invoke(Request request, Response response)',
      cname: 'grey',
      args: {
        id: '391',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'VOD.CDN-DOK',
        parentId: '387',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'doPost(HttpServletRequest request, HttpServletResponse response)',
      cname: 'grey',
      args: { id: '392', 'API Type': 'SPRING', 'Application Name': 'VOD.CDN-DOK', parentId: '391' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'bulk(String version, BulkRequest bulkRequest)',
      cname: 'grey',
      args: {
        id: '394',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.CDN-DOK',
        parentId: '392',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'list(BulkRequest request)',
      cname: 'grey',
      args: {
        id: '395',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.CDN-DOK',
        parentId: '394',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 3,
      id: '',
      ts: 1751350019348000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'video(CdnRequest request)',
      cname: 'grey',
      args: {
        id: '416',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.CDN-DOK',
        parentId: '395',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019342000,
      ph: 'X',
      dur: 4000,
      s: 'p',
      name: '[VOD.PLAYAPI3] connect()',
      cname: 'grey',
      args: {
        id: '423',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '386',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1751350019346000,
      ph: 'X',
      dur: 4000,
      s: 'p',
      name: 'getInputStream()',
      cname: 'grey',
      args: {
        id: '424',
        'API Type': 'JDK_HTTPCONNECTOR',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '384',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '9',
      ts: 1751350019341000,
      ph: 's',
      dur: 336000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '28',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '24',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '9',
      ts: 1751350019341000,
      ph: 'f',
      dur: 12000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: { id: '439', 'API Type': 'ASYNC', 'Application Name': 'VOD.PLAYAPI3', parentId: '438' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: 'grey',
      args: { id: '439', 'API Type': 'ASYNC', 'Application Name': 'VOD.PLAYAPI3', parentId: '438' },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'call()',
      cname: 'grey',
      args: {
        id: '440',
        'API Type': 'SPRING_ASYNC',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '439',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 12000,
      s: 'p',
      name: 'resolve(PlayContext context, Video video)',
      cname: 'grey',
      args: {
        id: '441',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '440',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019341000,
      ph: 'X',
      dur: 11000,
      s: 'p',
      name: 'getStatPolicy(PlayContext context, Video video)',
      cname: 'grey',
      args: {
        id: '442',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '441',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '',
      ts: 1751350019342000,
      ph: 'X',
      dur: 10000,
      s: 'p',
      name: 'intercept(Interceptor$Chain chain)',
      cname: 'grey',
      args: {
        id: '446',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '442',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 4,
      id: '10',
      ts: 1751350019346000,
      ph: 's',
      dur: 10000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '446',
        'API Type': 'OK_HTTP_CLIENT',
        'Application Name': 'VOD.PLAYAPI3',
        parentId: '442',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '10',
      ts: 1751350019346000,
      ph: 'f',
      dur: 6000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '448',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '446',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '',
      ts: 1751350019346000,
      ph: 'X',
      dur: 6000,
      s: 'p',
      name: '[APIGW-DEV-AD1] Vert.x HTTP Server',
      cname: '',
      args: {
        id: '448',
        'API Type': 'VERTX_HTTP_SERVER',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '446',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 5,
      id: '11',
      ts: 1751350019351000,
      ph: 's',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '355',
        'API Type': 'REACTOR_NETTY',
        'Application Name': 'VOD.NEXUS',
        parentId: '354',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '11',
      ts: 1751350019351000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '474',
        'API Type': 'ASYNC',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '457',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '',
      ts: 1751350019351000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: '',
      args: {
        id: '474',
        'API Type': 'ASYNC',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '457',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 6,
      id: '',
      ts: 1751350019351000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'handleResponse(HttpClientResponse resp, long timeoutMs)',
      cname: '',
      args: {
        id: '475',
        'API Type': 'VERTX_HTTP_CLIENT',
        'Application Name': 'APIGW-DEV-AD1',
        parentId: '474',
      },
      pid: '',
    },
  ],
};
