export const transactionInfo = {
  logLinkEnable: true,
  logButtonName: 'nelo',
  disableButtonMessage:
    "<p>해당 Transaction 과정에서 NELO에 전달된 로그 메시지는 없습니다.</p><p><a target='_blank' href='https://yobi.navercorp.com/pinpoint/posts/268'>PINPOINT NELO 연동 설정</a>을 하지 않았다면 설정 변경이 필요합니다.</p>",
  logPageUrl:
    'api/neloLog?transactionId=pgvacl01.apigw^1725513337166^59332810&spanId=-1122159368382224899&applicationName=ACL-PORTAL&time=1733730504248',
  transactionId: 'pgvacl01.apigw^1725513337166^59332810',
  spanId: -1122159368382224899,
  completeState: 'Complete',
  applicationId: 'ACL-PORTAL',
  callStackStart: 1733730504248,
  callStackEnd: 1733730504264,
  callStackIndex: {
    depth: 0,
    begin: 1,
    end: 2,
    excludeFromTimeline: 3,
    applicationName: 4,
    tab: 5,
    id: 6,
    parentId: 7,
    isMethod: 8,
    hasChild: 9,
    title: 10,
    arguments: 11,
    executeTime: 12,
    gap: 13,
    elapsedTime: 14,
    barWidth: 15,
    executionMilliseconds: 16,
    simpleClassName: 17,
    methodType: 18,
    apiType: 19,
    agent: 20,
    isFocused: 21,
    hasException: 22,
    isAuthorized: 23,
    agentName: 24,
    lineNumber: 25,
    location: 26,
    applicationServiceType: 27,
    exceptionChainId: 28,
  },
  callStack: [
    [
      '',
      1733730504248,
      1733730504263,
      false,
      'ACL-PORTAL',
      0,
      '1',
      '',
      true,
      true,
      'Servlet Process',
      '/api/v2/acls/likeit',
      '16:48:24 248',
      '0',
      '15',
      '90',
      '0',
      '',
      '100',
      'TOMCAT',
      'pgvacl01.apigw',
      true,
      false,
      true,
      ' ',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      1,
      '2',
      '1',
      false,
      false,
      'http.status.code',
      '304',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      1,
      '3',
      '1',
      false,
      false,
      'PROXY(NGINX)',
      '0ms ago(16:48:24 248)',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      1,
      '4',
      '1',
      false,
      false,
      'PROXY(NGINX)',
      '0ms ago(16:48:24 248)',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      1,
      '5',
      '1',
      false,
      false,
      'REMOTE_ADDRESS',
      '10.159.82.184',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      1,
      '6',
      '1',
      false,
      false,
      'ENDPOINT',
      'acl-portal.navercorp.com:80',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504263,
      false,
      'ACL-PORTAL',
      1,
      '7',
      '1',
      true,
      false,
      'invoke(Request request, Response response)',
      '',
      '16:48:24 248',
      '0',
      '15',
      '90',
      '0',
      'StandardHostValve',
      '0',
      'TOMCAT_METHOD',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      98,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504248,
      false,
      'ACL-PORTAL',
      2,
      '8',
      '7',
      true,
      false,
      'doSubmit(Callable task, AsyncTaskExecutor executor, Class returnType)',
      '',
      '16:48:24 248',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionAspectSupport',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      273,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504248,
      false,
      'ACL-PORTAL',
      3,
      '9',
      '8',
      true,
      false,
      'Asynchronous Invocation',
      '',
      '16:48:24 248',
      '0',
      '0',
      '0',
      '0',
      '',
      '200',
      'ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504248,
      false,
      'ACL-PORTAL',
      4,
      '10',
      '9',
      true,
      false,
      'call()',
      '',
      '16:48:24 248',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionInterceptor$$Lambda$1417',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504263,
      false,
      'ACL-PORTAL',
      2,
      '11',
      '7',
      true,
      false,
      'doGet(HttpServletRequest request, HttpServletResponse response)',
      '',
      '16:48:24 248',
      '0',
      '15',
      '90',
      '0',
      'FrameworkServlet',
      '0',
      'SPRING',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      898,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504263,
      false,
      'ACL-PORTAL',
      3,
      '12',
      '11',
      true,
      false,
      'getAclsV2ByProviderId(String providerId, long updateTime, HttpServletRequest request)',
      '',
      '16:48:24 248',
      '0',
      '15',
      '90',
      '0',
      'ExternalApiController',
      '0',
      'SPRING_BEAN',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      163,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504263,
      false,
      'ACL-PORTAL',
      4,
      '13',
      '12',
      true,
      false,
      'invokeWithinTransaction(Method method, Class targetClass, TransactionAspectSupport$InvocationCallback invocation)',
      '',
      '16:48:24 248',
      '0',
      '15',
      '90',
      '9',
      'TransactionAspectSupport',
      '0',
      'SPRING_TX',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      334,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504251,
      false,
      'ACL-PORTAL',
      5,
      '14',
      '13',
      true,
      false,
      'getConnection()',
      '',
      '16:48:24 248',
      '0',
      '3',
      '18',
      '0',
      'BasicDataSource',
      '0',
      'DBCP2',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      1521,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504248,
      1733730504251,
      false,
      'ACL-PORTAL',
      6,
      '15',
      '14',
      true,
      false,
      'executeQuery()',
      '',
      '16:48:24 248',
      '0',
      '3',
      '18',
      '3',
      'ClientPreparedStatement',
      '0',
      'MYSQL(acl)',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      958,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      7,
      '16',
      '15',
      false,
      false,
      'SQL',
      'SQL-ID not found sqlId:1024',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504254,
      1733730504257,
      false,
      'ACL-PORTAL',
      5,
      '17',
      '13',
      true,
      false,
      'findByIdAndStatusTrue(String id)',
      '',
      '16:48:24 254',
      '3',
      '3',
      '18',
      '0',
      'ProviderService',
      '0',
      'SPRING_BEAN',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      85,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504254,
      1733730504257,
      false,
      'ACL-PORTAL',
      6,
      '18',
      '17',
      true,
      false,
      'invokeWithinTransaction(Method method, Class targetClass, TransactionAspectSupport$InvocationCallback invocation)',
      '',
      '16:48:24 254',
      '0',
      '3',
      '18',
      '0',
      'TransactionAspectSupport',
      '0',
      'SPRING_TX',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      334,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504254,
      1733730504257,
      false,
      'ACL-PORTAL',
      7,
      '19',
      '18',
      true,
      false,
      'executeQuery()',
      '',
      '16:48:24 254',
      '0',
      '3',
      '18',
      '3',
      'ClientPreparedStatement',
      '0',
      'MYSQL(acl)',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      958,
      '',
      '',
      '0',
    ],
    [
      '',
      0,
      0,
      false,
      null,
      8,
      '20',
      '19',
      false,
      false,
      'SQL',
      'SQL-ID not found sqlId:1025',
      '',
      '',
      '',
      '',
      '',
      '',
      '0',
      '',
      null,
      false,
      false,
      true,
      null,
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      5,
      '21',
      '13',
      true,
      false,
      'close()',
      '',
      '16:48:24 263',
      '6',
      '0',
      '0',
      '0',
      'PoolingDataSource$PoolGuardConnectionWrapper',
      '0',
      'DBCP2',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      243,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      4,
      '22',
      '12',
      true,
      false,
      'findApiSecurityDtoV2ByProvider(Provider provider, long providerUpdateTime, HttpServletRequest request)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AclConfigService',
      '0',
      'SPRING_BEAN',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      138,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      2,
      '23',
      '7',
      true,
      false,
      'doSubmit(Callable task, AsyncTaskExecutor executor, Class returnType)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionAspectSupport',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      273,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504264,
      false,
      'ACL-PORTAL',
      3,
      '24',
      '23',
      true,
      false,
      'Asynchronous Invocation',
      '',
      '16:48:24 263',
      '0',
      '1',
      '6',
      '0',
      '',
      '200',
      'ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504264,
      false,
      'ACL-PORTAL',
      4,
      '25',
      '24',
      true,
      false,
      'call()',
      '',
      '16:48:24 263',
      '0',
      '1',
      '6',
      '1',
      'AsyncExecutionInterceptor$$Lambda$1417',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      5,
      '26',
      '25',
      true,
      false,
      'hsetnx(Object key, Object field, Object value)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AbstractRedisAsyncCommands',
      '0',
      'REDIS',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      1041,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504264,
      1733730504264,
      false,
      'ACL-PORTAL',
      5,
      '27',
      '25',
      true,
      false,
      'hincrby(Object key, Object field, long amount)',
      '',
      '16:48:24 264',
      '1',
      '0',
      '0',
      '0',
      'AbstractRedisAsyncCommands',
      '0',
      'REDIS',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      930,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      2,
      '28',
      '7',
      true,
      false,
      'doSubmit(Callable task, AsyncTaskExecutor executor, Class returnType)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionAspectSupport',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      273,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504264,
      false,
      'ACL-PORTAL',
      3,
      '29',
      '28',
      true,
      false,
      'Asynchronous Invocation',
      '',
      '16:48:24 263',
      '0',
      '1',
      '6',
      '0',
      '',
      '200',
      'ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504264,
      false,
      'ACL-PORTAL',
      4,
      '30',
      '29',
      true,
      false,
      'call()',
      '',
      '16:48:24 263',
      '0',
      '1',
      '6',
      '1',
      'AsyncExecutionInterceptor$$Lambda$1417',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      5,
      '31',
      '30',
      true,
      false,
      'hsetnx(Object key, Object field, Object value)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AbstractRedisAsyncCommands',
      '0',
      'REDIS',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      1041,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504264,
      1733730504264,
      false,
      'ACL-PORTAL',
      5,
      '32',
      '30',
      true,
      false,
      'hincrby(Object key, Object field, long amount)',
      '',
      '16:48:24 264',
      '1',
      '0',
      '0',
      '0',
      'AbstractRedisAsyncCommands',
      '0',
      'REDIS',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      930,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      2,
      '33',
      '7',
      true,
      false,
      'doSubmit(Callable task, AsyncTaskExecutor executor, Class returnType)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionAspectSupport',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      273,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      3,
      '34',
      '33',
      true,
      false,
      'Asynchronous Invocation',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      '',
      '200',
      'ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      4,
      '35',
      '34',
      true,
      false,
      'call()',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionInterceptor$$Lambda$1417',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      2,
      '36',
      '7',
      true,
      false,
      'doSubmit(Callable task, AsyncTaskExecutor executor, Class returnType)',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionAspectSupport',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      273,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      3,
      '37',
      '36',
      true,
      false,
      'Asynchronous Invocation',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      '',
      '200',
      'ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
    [
      '',
      1733730504263,
      1733730504263,
      false,
      'ACL-PORTAL',
      4,
      '38',
      '37',
      true,
      false,
      'call()',
      '',
      '16:48:24 263',
      '0',
      '0',
      '0',
      '0',
      'AsyncExecutionInterceptor$$Lambda$1417',
      '0',
      'SPRING_ASYNC',
      'pgvacl01.apigw',
      false,
      false,
      true,
      '',
      0,
      '',
      '',
      '0',
    ],
  ],
  loggingTransactionInfo: false,
  applicationMapData: {
    nodeDataArray: [
      {
        key: 'ACL-PORTAL^SPRING_BOOT',
        applicationName: 'ACL-PORTAL',
        category: 'SPRING_BOOT',
        serviceType: 'SPRING_BOOT',
        serviceTypeCode: 1210,
        isWas: true,
        isQueue: false,
        isAuthorized: true,
        totalCount: 1,
        errorCount: 0,
        slowCount: 0,
        hasAlert: false,
        responseStatistics: {
          Tot: 1,
          Sum: 15,
          Avg: 15,
          Max: 15,
        },
        histogram: {
          '1s': 1,
          '3s': 0,
          '5s': 0,
          Slow: 0,
          Error: 0,
        },
        agentHistogram: {
          'pgvacl01.apigw': {
            '1s': 1,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        agentResponseStatistics: {
          'pgvacl01.apigw': {
            Tot: 1,
            Sum: 15,
            Avg: 15,
            Max: 15,
          },
        },
        timeSeriesHistogram: [
          {
            key: '1s',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
          {
            key: '3s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '5s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
        ],
        agentTimeSeriesHistogram: {
          'pgvacl01.apigw': [
            {
              key: '1s',
              values: [
                [0, 0],
                [1733730480000, 1],
              ],
            },
            {
              key: '3s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '5s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 1],
              ],
            },
          ],
        },
        instanceCount: 0,
        instanceErrorCount: 0,
        agentIds: [],
        agentIdNameMap: {},
        serverList: {},
      },
      {
        key: 'REDIS_LETTUCE^REDIS',
        applicationName: 'REDIS_LETTUCE',
        category: 'REDIS',
        serviceType: 'REDIS',
        serviceTypeCode: 8201,
        isWas: false,
        isQueue: false,
        isAuthorized: true,
        totalCount: 4,
        errorCount: 0,
        slowCount: 0,
        hasAlert: false,
        responseStatistics: {
          Tot: 4,
          Sum: 0,
          Avg: 0,
          Max: 0,
        },
        histogram: {
          '100ms': 4,
          '300ms': 0,
          '500ms': 0,
          Slow: 0,
          Error: 0,
        },
        agentHistogram: {
          UNKNOWN: {
            '100ms': 4,
            '300ms': 0,
            '500ms': 0,
            Slow: 0,
            Error: 0,
          },
        },
        agentResponseStatistics: {
          UNKNOWN: {
            Tot: 4,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        timeSeriesHistogram: [
          {
            key: '100ms',
            values: [
              [0, 0],
              [1733730480000, 4],
            ],
          },
          {
            key: '300ms',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '500ms',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 4],
            ],
          },
        ],
        agentTimeSeriesHistogram: {
          UNKNOWN: [
            {
              key: '100ms',
              values: [
                [0, 0],
                [1733730480000, 4],
              ],
            },
            {
              key: '300ms',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '500ms',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 4],
              ],
            },
          ],
        },
        instanceCount: 1,
        instanceErrorCount: 0,
        agentIds: ['UNKNOWN'],
        agentIdNameMap: {
          UNKNOWN: null,
        },
        serverList: {
          UNKNOWN: {
            name: 'UNKNOWN',
            status: null,
            linkList: [],
            instanceList: {
              UNKNOWN: {
                hasInspector: false,
                name: 'UNKNOWN',
                agentName: null,
                serviceType: 'REDIS_LETTUCE',
                status: {
                  code: -1,
                  desc: 'Unknown',
                },
              },
            },
          },
        },
      },
      {
        key: 'acl^MYSQL',
        applicationName: 'acl',
        category: 'MYSQL',
        serviceType: 'MYSQL',
        serviceTypeCode: 2101,
        isWas: false,
        isQueue: false,
        isAuthorized: true,
        totalCount: 2,
        errorCount: 0,
        slowCount: 0,
        hasAlert: false,
        responseStatistics: {
          Tot: 2,
          Sum: 0,
          Avg: 0,
          Max: 0,
        },
        histogram: {
          '1s': 2,
          '3s': 0,
          '5s': 0,
          Slow: 0,
          Error: 0,
        },
        agentHistogram: {
          'mysql-W310ctt.db-nfra.io:13306': {
            '1s': 2,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        agentResponseStatistics: {
          'mysql-W310ctt.db-nfra.io:13306': {
            Tot: 2,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        timeSeriesHistogram: [
          {
            key: '1s',
            values: [
              [0, 0],
              [1733730480000, 2],
            ],
          },
          {
            key: '3s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '5s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 2],
            ],
          },
        ],
        agentTimeSeriesHistogram: {
          'mysql-W310ctt.db-nfra.io:13306': [
            {
              key: '1s',
              values: [
                [0, 0],
                [1733730480000, 2],
              ],
            },
            {
              key: '3s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '5s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 2],
              ],
            },
          ],
        },
        instanceCount: 1,
        instanceErrorCount: 0,
        agentIds: ['mysql-W310ctt.db-nfra.io:13306'],
        agentIdNameMap: {
          'mysql-W310ctt.db-nfra.io:13306': null,
        },
        serverList: {
          'mysql-W310ctt.db-nfra.io': {
            name: 'mysql-W310ctt.db-nfra.io',
            status: null,
            linkList: [],
            instanceList: {
              'mysql-W310ctt.db-nfra.io:13306': {
                hasInspector: false,
                name: 'mysql-W310ctt.db-nfra.io:13306',
                agentName: null,
                serviceType: 'MYSQL_EXECUTE_QUERY',
                status: {
                  code: -1,
                  desc: 'Unknown',
                },
              },
            },
          },
        },
      },
      {
        key: 'ACL-PORTAL^USER',
        applicationName: 'USER',
        category: 'USER',
        serviceType: 'USER',
        serviceTypeCode: 2,
        isWas: false,
        isQueue: false,
        isAuthorized: true,
        totalCount: 1,
        errorCount: 0,
        slowCount: 0,
        hasAlert: false,
        responseStatistics: {
          Tot: 1,
          Sum: 15,
          Avg: 15,
          Max: 15,
        },
        histogram: {
          '1s': 1,
          '3s': 0,
          '5s': 0,
          Slow: 0,
          Error: 0,
        },
        agentHistogram: {},
        agentResponseStatistics: {},
        timeSeriesHistogram: [
          {
            key: '1s',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
          {
            key: '3s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '5s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
        ],
        agentTimeSeriesHistogram: {},
        instanceCount: 0,
        instanceErrorCount: 0,
        agentIds: [],
        agentIdNameMap: {},
        serverList: {},
      },
    ],
    linkDataArray: [
      {
        key: 'ACL-PORTAL^USER~ACL-PORTAL^SPRING_BOOT',
        from: 'ACL-PORTAL^USER',
        to: 'ACL-PORTAL^SPRING_BOOT',
        toAgent: [],
        toAgentIdNameMap: {},
        sourceInfo: {
          applicationName: 'ACL-PORTAL',
          serviceType: 'USER',
          serviceTypeCode: 2,
          isWas: false,
        },
        targetInfo: {
          applicationName: 'ACL-PORTAL',
          serviceType: 'SPRING_BOOT',
          serviceTypeCode: 1210,
          isWas: true,
        },
        filterApplicationName: 'ACL-PORTAL',
        filterApplicationServiceTypeCode: 1210,
        filterApplicationServiceTypeName: 'SPRING_BOOT',
        totalCount: 1,
        errorCount: 0,
        slowCount: 0,
        responseStatistics: {
          Tot: 1,
          Sum: 15,
          Avg: 15,
          Max: 15,
        },
        histogram: {
          '1s': 1,
          '3s': 0,
          '5s': 0,
          Slow: 0,
          Error: 0,
        },
        timeSeriesHistogram: [
          {
            key: '1s',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
          {
            key: '3s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '5s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 15],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 1],
            ],
          },
        ],
        sourceHistogram: {
          'pgvacl01.apigw': {
            '1s': 1,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        targetHistogram: {
          'pgvacl01.apigw': {
            '1s': 1,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        sourceTimeSeriesHistogram: {
          'pgvacl01.apigw': [
            {
              key: '1s',
              values: [
                [0, 0],
                [1733730480000, 1],
              ],
            },
            {
              key: '3s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '5s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 15],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 1],
              ],
            },
          ],
        },
        sourceResponseStatistics: {
          'pgvacl01.apigw': {
            Tot: 1,
            Sum: 15,
            Avg: 15,
            Max: 15,
          },
        },
        targetResponseStatistics: {
          'pgvacl01.apigw': {
            Tot: 1,
            Sum: 15,
            Avg: 15,
            Max: 15,
          },
        },
        hasAlert: false,
      },
      {
        key: 'ACL-PORTAL^SPRING_BOOT~REDIS_LETTUCE^REDIS',
        from: 'ACL-PORTAL^SPRING_BOOT',
        to: 'REDIS_LETTUCE^REDIS',
        fromAgent: [],
        fromAgentIdNameMap: {},
        sourceInfo: {
          applicationName: 'ACL-PORTAL',
          serviceType: 'SPRING_BOOT',
          serviceTypeCode: 1210,
          isWas: true,
        },
        targetInfo: {
          applicationName: 'REDIS_LETTUCE',
          serviceType: 'REDIS',
          serviceTypeCode: 8201,
          isWas: false,
        },
        filterApplicationName: 'ACL-PORTAL',
        filterApplicationServiceTypeCode: 1210,
        filterApplicationServiceTypeName: 'SPRING_BOOT',
        totalCount: 4,
        errorCount: 0,
        slowCount: 0,
        responseStatistics: {
          Tot: 4,
          Sum: 0,
          Avg: 0,
          Max: 0,
        },
        histogram: {
          '100ms': 4,
          '300ms': 0,
          '500ms': 0,
          Slow: 0,
          Error: 0,
        },
        timeSeriesHistogram: [
          {
            key: '100ms',
            values: [
              [0, 0],
              [1733730480000, 4],
            ],
          },
          {
            key: '300ms',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '500ms',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 4],
            ],
          },
        ],
        sourceHistogram: {
          'pgvacl01.apigw': {
            '100ms': 4,
            '300ms': 0,
            '500ms': 0,
            Slow: 0,
            Error: 0,
          },
        },
        targetHistogram: {
          UNKNOWN: {
            '100ms': 4,
            '300ms': 0,
            '500ms': 0,
            Slow: 0,
            Error: 0,
          },
        },
        sourceTimeSeriesHistogram: {
          'pgvacl01.apigw': [
            {
              key: '100ms',
              values: [
                [0, 0],
                [1733730480000, 4],
              ],
            },
            {
              key: '300ms',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '500ms',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 4],
              ],
            },
          ],
        },
        sourceResponseStatistics: {
          'pgvacl01.apigw': {
            Tot: 4,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        targetResponseStatistics: {
          UNKNOWN: {
            Tot: 4,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        hasAlert: false,
      },
      {
        key: 'ACL-PORTAL^SPRING_BOOT~acl^MYSQL',
        from: 'ACL-PORTAL^SPRING_BOOT',
        to: 'acl^MYSQL',
        fromAgent: [],
        fromAgentIdNameMap: {},
        sourceInfo: {
          applicationName: 'ACL-PORTAL',
          serviceType: 'SPRING_BOOT',
          serviceTypeCode: 1210,
          isWas: true,
        },
        targetInfo: {
          applicationName: 'acl',
          serviceType: 'MYSQL',
          serviceTypeCode: 2101,
          isWas: false,
        },
        filterApplicationName: 'ACL-PORTAL',
        filterApplicationServiceTypeCode: 1210,
        filterApplicationServiceTypeName: 'SPRING_BOOT',
        totalCount: 2,
        errorCount: 0,
        slowCount: 0,
        responseStatistics: {
          Tot: 2,
          Sum: 0,
          Avg: 0,
          Max: 0,
        },
        histogram: {
          '1s': 2,
          '3s': 0,
          '5s': 0,
          Slow: 0,
          Error: 0,
        },
        timeSeriesHistogram: [
          {
            key: '1s',
            values: [
              [0, 0],
              [1733730480000, 2],
            ],
          },
          {
            key: '3s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: '5s',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Slow',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Error',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Avg',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Max',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Sum',
            values: [
              [0, 0],
              [1733730480000, 0],
            ],
          },
          {
            key: 'Tot',
            values: [
              [0, 0],
              [1733730480000, 2],
            ],
          },
        ],
        sourceHistogram: {
          'pgvacl01.apigw': {
            '1s': 2,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        targetHistogram: {
          'mysql-W310ctt.db-nfra.io:13306': {
            '1s': 2,
            '3s': 0,
            '5s': 0,
            Slow: 0,
            Error: 0,
          },
        },
        sourceTimeSeriesHistogram: {
          'pgvacl01.apigw': [
            {
              key: '1s',
              values: [
                [0, 0],
                [1733730480000, 2],
              ],
            },
            {
              key: '3s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: '5s',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Slow',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Error',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Avg',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Max',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Sum',
              values: [
                [0, 0],
                [1733730480000, 0],
              ],
            },
            {
              key: 'Tot',
              values: [
                [0, 0],
                [1733730480000, 2],
              ],
            },
          ],
        },
        sourceResponseStatistics: {
          'pgvacl01.apigw': {
            Tot: 2,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        targetResponseStatistics: {
          'mysql-W310ctt.db-nfra.io:13306': {
            Tot: 2,
            Sum: 0,
            Avg: 0,
            Max: 0,
          },
        },
        hasAlert: false,
      },
    ],
  },
  agentId: 'pgvacl01.apigw',
  applicationName: '/api/v2/acls/likeit',
  agentName: ' ',
};

export const traceViewData = {
  traceEvents: [
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 15000,
      s: 'p',
      name: '[ACL-PORTAL] Servlet Process',
      cname: '',
      args: {
        id: '1',
        'API Type': 'TOMCAT',
        'Application Name': 'ACL-PORTAL',
        parentId: '0',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 15000,
      s: 'p',
      name: 'invoke(Request request, Response response)',
      cname: '',
      args: {
        id: '7',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'ACL-PORTAL',
        parentId: '1',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 15000,
      s: 'p',
      name: 'doGet(HttpServletRequest request, HttpServletResponse response)',
      cname: '',
      args: {
        id: '11',
        'API Type': 'SPRING',
        'Application Name': 'ACL-PORTAL',
        parentId: '7',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 15000,
      s: 'p',
      name: 'getAclsV2ByProviderId(String providerId, long updateTime, HttpServletRequest request)',
      cname: '',
      args: {
        id: '12',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'ACL-PORTAL',
        parentId: '11',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 15000,
      s: 'p',
      name: 'invokeWithinTransaction(Method method, Class targetClass, TransactionAspectSupport$InvocationCallback invocation)',
      cname: '',
      args: {
        id: '13',
        'API Type': 'SPRING_TX',
        'Application Name': 'ACL-PORTAL',
        parentId: '12',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'getConnection()',
      cname: '',
      args: {
        id: '14',
        'API Type': 'DBCP2',
        'Application Name': 'ACL-PORTAL',
        parentId: '13',
      },
      pid: '',
    },
    {
      cat: 'Database',
      tid: 0,
      id: '',
      ts: 1733730504248000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'executeQuery()',
      cname: '',
      args: {
        Query: 'SQL-ID not found sqlId:1024',
        id: '15',
        'API Type': 'MYSQL(acl)',
        'Application Name': 'ACL-PORTAL',
        parentId: '14',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504254000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'findByIdAndStatusTrue(String id)',
      cname: '',
      args: {
        id: '17',
        'API Type': 'SPRING_BEAN',
        'Application Name': 'ACL-PORTAL',
        parentId: '13',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '',
      ts: 1733730504254000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'invokeWithinTransaction(Method method, Class targetClass, TransactionAspectSupport$InvocationCallback invocation)',
      cname: '',
      args: {
        id: '18',
        'API Type': 'SPRING_TX',
        'Application Name': 'ACL-PORTAL',
        parentId: '17',
      },
      pid: '',
    },
    {
      cat: 'Database',
      tid: 0,
      id: '',
      ts: 1733730504254000,
      ph: 'X',
      dur: 3000,
      s: 'p',
      name: 'executeQuery()',
      cname: '',
      args: {
        Query: 'SQL-ID not found sqlId:1025',
        id: '19',
        'API Type': 'MYSQL(acl)',
        'Application Name': 'ACL-PORTAL',
        parentId: '18',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '0',
      ts: 1733730504263000,
      ph: 's',
      dur: 15000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '7',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'ACL-PORTAL',
        parentId: '1',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '0',
      ts: 1733730504263000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '24',
        'API Type': 'ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '23',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1733730504263000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: '',
      args: {
        id: '24',
        'API Type': 'ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '23',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 1,
      id: '',
      ts: 1733730504263000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'call()',
      cname: '',
      args: {
        id: '25',
        'API Type': 'SPRING_ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '24',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 0,
      id: '1',
      ts: 1733730504263000,
      ph: 's',
      dur: 15000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '7',
        'API Type': 'TOMCAT_METHOD',
        'Application Name': 'ACL-PORTAL',
        parentId: '1',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '1',
      ts: 1733730504263000,
      ph: 'f',
      dur: 1000,
      s: 'p',
      name: 'Async Trace',
      cname: '',
      args: {
        id: '29',
        'API Type': 'ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '28',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1733730504263000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'Asynchronous Invocation',
      cname: '',
      args: {
        id: '29',
        'API Type': 'ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '28',
      },
      pid: '',
    },
    {
      cat: 'Trace',
      tid: 2,
      id: '',
      ts: 1733730504263000,
      ph: 'X',
      dur: 1000,
      s: 'p',
      name: 'call()',
      cname: '',
      args: {
        id: '30',
        'API Type': 'SPRING_ASYNC',
        'Application Name': 'ACL-PORTAL',
        parentId: '29',
      },
      pid: '',
    },
  ],
};
